version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@2.2.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run postbuild

  docker-build:
    docker:
      - image: docker
    steps:
      - checkout
      - docker/publish:
            registry: '625831105170.dkr.ecr.ap-south-1.amazonaws.com' 
            use-docker-credentials-store: false 
            deploy: true 
            image: portfolio-abh80 
            aws-access-key-id: $AWS_ACCESS_KEY_ID
            aws-secret-access-key: $AWS_SECRET_ACCESS_KEY
      
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                new
      - docker-build:
          requires:
            - build
        
        