version: 2.1

orbs:
  node: circleci/node@4.7
  aws-cli: circleci/aws-cli@2.0.3
  docker: circleci/docker@1.7.0

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run postbuild

  docker-build:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - docker/install-docker
      - run: 
          name: Login docker to AWS ECR
          command: $(aws ecr get-login-password --region $region) | docker login --username AWS --password-stdin $ecr
      - run:
          name: Build Docker File
          command : |
            echo "Building docker file..."
            docker build -t ${ecr}:${CIRCLE_SHA1} .
      - run:
          name: Push Docker Image
          command: |
            echo "Pushing image..."
            docker push ${ecr}:${CIRCLE_SHA1}

      
      
      

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                new
      - docker-build
        
        