version: 2.1

orbs:
  node: circleci/node@4.7
  docker: circleci/docker@1.7.0
  aws-ecr: circleci/aws-ecr@8.2.1

jobs:
  build:
    docker:
      - image: cimg/node:16.10
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run postbuild

  docker-build:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
            repo: portfolio-abh80 
            assume-web-identity: false 
            attach-workspace: false 
            checkout: true 
            create-repo: false 
            docker-login: false 
            public-registry: false 
            push-image: true 
            remote-docker-layer-caching: false 
            repo-scan-on-push: true 
            set-repo-policy: false 
            setup-remote-docker: false 
            skip-when-tags-exist: false 
            region: $region 
            tag: ${CIRCLE_SHA1} 

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                new
      - docker-build:
          requires:
            - build
        
        